# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- development

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AngularDemo/memesaver'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'Yoink_SonarCloud_Connection'
    organization: yoinkp3
    projectKey: 'YoinkP3_Yoink-Pipeline  '
    projectName: 'Yoink Pipeline '

- task: NodeTool@0
  displayName: 'Use Node 16.x'
  inputs:
    versionSpec: 16.x

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: client
    verbose: false

- task: RaulARuiz.angular-cli-1.angular-cli-build-task.AngularCLI@1
  displayName: 'ng build'
  inputs:
    project: client

- task: RaulARuiz.angular-cli-1.angular-cli-build-task.AngularCLI@1
  displayName: 'ng test'
  inputs:
    command: test
    project: client

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'


